language: elixir

elixir: '1.7.4'

# See https://repo.hex.pm/builds/elixir/builds.txt for available versions
jobs:
  include:
    - elixir: '1.8.2'
      otp_release: '20'
    - elixir: '1.9.4'
      otp_release: '20'
    - elixir: '1.10.4'
      otp_release: '21'
    - elixir: '1.11.2'
      otp_release: '21'

env:
  - MIX_ENV=test

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - MIX_ENV=docs mix do deps.get, inch.report
